# GitHub Actions configuration **EXAMPLE**,
# MODIFY IT ACCORDING TO YOUR NEEDS!
# Reference: https://docs.github.com/en/actions

name: tests

on:
  push:
    branches: [main]
  pull_request:  # Run in every PR
  workflow_dispatch:  # Allow manually triggering the workflow

concurrency:
  group: >-
    ${{ github.workflow }}-${{ github.ref_type }}-
    ${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: {fetch-depth: 0}
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: |
            **/requirements/dev.txt
            **/requirements/prod.txt
      - name: Update pip
        run: pip install --upgrade pip
      - name: Initialize application
        run: make init
      - name: Lint
        run: make lint-ci
      - name: Check packages
        run: pip freeze

  test:
    needs: prepare
    strategy:
      matrix:
        python:
        - "3.10"
        platform:
        - ubuntu-latest
        - macos-latest
        - windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"
          cache-dependency-path: |
            **/requirements/dev.txt
            **/requirements/prod.txt
      - name: Initialize application
        run: make init
      - name: Check packages
        run: pip freeze
      - name: Test
        run: make test-ci
      - name: Store coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-${{ matrix.platform }}
          path: htmlcov/
